private["_intelItems", "_intel", "_used", "_ID", "_cases", "_case", "_cache", "_marker"];
	params ["_intel"]; 
	_intelItems=["Land_PCSet_01_case_F"];
	_intel = _this select 0;
	_used =_this select 1;
	_ID =_this select 2;
	_marker = _this select 3;
	deleteMarker "Intel";
	_cases=nearestObjects[getPosATL player,_intelItems,3];
	if(count _cases==0)exitWith{};
	_intel removeAction _ID;
	_case=_cases select 0;
	if isNull _case exitWith{};
	deleteVehicle _case;player groupChat "I have obtained Russian intel.";
	_cache=cache;
	if(isNil "_cache")exitWith{hint "Intel suggests this place is clean.  Better check elsewhere.";};
	[nil,"iHint",true,false]spawn BIS_fnc_MP;
	[_cache,"addIMkr",false,false]spawn BIS_fnc_MP;
	[] execVM "core\modules\cacheScript\createIntel.sqf";